# SPDX-License-Identifier: Apache-2.0
# Provisions the Prometheus datasource so the dashboard works on first start.
apiVersion: 1

datasources:
  - name: Prometheus
    uid: prom-gnmi
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 5s
